### ISSUE TITLE
Cannot commit on fork

### ISSUE THREAD

**Issue by Stigmi** [PrestaShop/bpostshm#19]
Hello,

We would like to commit the new 1.21 version but we did not manage to do so.

**commands:**

git checkout -b newdev
git push origin newdev

**full error:**

remote: Permission to PrestaShop/bpostshm.git denied to git@stigmi.eu.
fatal: unable to access 'https://github.com/PrestaShop/bpostshm.git/': The requested URL returned error: 403

Could you tell us where/how we are supposed to commit the upgrade?
Thank you

**Comment by Quetzacoalt91** [comment]
Hi @Stigmi,

You have to create PR. When the repository was made public, your write access has been revoked.

Best regards

**Comment by Stigmi** [comment]
Sure but on which branch?
We tried to create a new one ("newdev") but had the permission issue described above.
Thx

**Comment by Quetzacoalt91** [comment]
On the branch you want, but on your fork !

You cannot push directly on PrestaShop/bpostshm, you have you to push the changes on your fork (https://github.com/Stigmi/bpostshm-1), and then create a pull-request.

If needed, here is a link which can help you: https://help.github.com/articles/using-pull-requests/

Best regards

**Comment by Stigmi** [comment]
We were not aware of https://github.com/Stigmi/bpostshm-1
Thank you for your help!

**Comment by Quetzacoalt91** [comment]
Great, do not forget to synchronise it with PrestaShop/bpostshm. It can be outdated ;)

https://help.github.com/articles/syncing-a-fork/
