### ISSUE TITLE
Delivery point selection not working with SSL

### ISSUE THREAD

**Issue by Tito1337** [PrestaShop/bpostshm#20]
Hello,

When Prestashop is set to have SSL enable, but not on all pages, the order confirmation process is secured by SSL.

But the bpostshm module does not consider this. When you have to select a delivery point (either @bpost or @24/7), the module opens a fancybox that calls to non-HTTPS elements. Browser security policy will block all these calls.

So this module is mostly non-working with HTTPS-enabled Prestashops.

**Comment by Stigmi** [comment]
Hello Tito,

Thank you for your input, we'll review and test your fix.

At the moment, we advised using "Force SSL" configuration to overcome this issue.

A proper fix would be much better.
